-- AlterTable
ALTER TABLE "MetaField" ALTER COLUMN "keywords" SET NOT NULL,
ALTER COLUMN "keywords" SET DATA TYPE TEXT,
ALTER COLUMN "hreflang" SET NOT NULL,
ALTER COLUMN "hreflang" SET DATA TYPE TEXT;
