# Use official PostgreSQL image
FROM postgres:15

# Set environment variables used in prisma service
ENV POSTGRES_DB = yag_ve_yag_test
ENV POSTGRES_USER = postgres
ENV POSTGRES_PASSWORD = 4784961ed

# Expose the PostgreSQL port
EXPOSE 5432